FROM node:16 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

RUN apk add --no-cache nodejs npm && npm install -g json-server

COPY --from=build /app/dist /usr/share/nginx/html

COPY public/products.json /app/products.json

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000 3001

CMD sh -c "nginx -g 'daemon off;' & json-server --watch /app/products.json --port 3001"
